"""Gerrit review payload publisher."""

from __future__ import annotations

import os
from typing import Any, Mapping, cast

from ai_code_review.diff.sources.base import DiffSourceError
from ai_code_review.diff.sources.gerrit import (
    GerritTarget,
    gerrit_rest_id,
    parse_gerrit_identifier,
)
from ai_code_review.publish.base import (
    PublishMode,
    PublishResult,
    ReviewPayload,
    ReviewPublisherError,
)
from ai_code_review.publish.format import (
    build_inline_comment_text,
    build_summary_comment,
    review_fingerprint,
)


def _as_list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def build_gerrit_review_payload(review: ReviewPayload, fingerprint: str) -> dict[str, Any]:
    """Build Gerrit's review input shape with per-line comments."""
    comments: dict[str, list[dict[str, Any]]] = {}
    for raw_item in _as_list(review.get("findings")):
        if not isinstance(raw_item, Mapping):
            continue
        item = cast(Mapping[str, Any], raw_item)
        file_path = item.get("file")
        line = item.get("line")
        if not file_path or not isinstance(line, int):
            continue
        comments.setdefault(str(file_path), []).append(
            {
                "line": line,
                "message": build_inline_comment_text(item),
                "unresolved": True,
            }
        )

    return {
        "message": build_summary_comment(review, fingerprint=fingerprint),
        "tag": "autogenerated:ai-code-review",
        "comments": comments,
    }


class GerritPublisher:
    """Publishes Gerrit review input or returns it as a dry-run payload."""

    def __init__(
        self,
        *,
        target: str | None = None,
        auth_token: str | None = None,
        session_factory: Any | None = None,
    ) -> None:
        self._target = target
        self._auth_token = (
            auth_token if auth_token is not None else os.environ.get("GERRIT_AUTH_TOKEN")
        )
        self._session_factory = session_factory or self._default_session_factory

    @staticmethod
    def _default_session_factory() -> Any:
        import aiohttp

        return aiohttp.ClientSession()

    def _headers(self) -> dict[str, str]:
        headers = {"Content-Type": "application/json"}
        if self._auth_token:
            headers["Authorization"] = f"Bearer {self._auth_token}"
        return headers

    def _target_from_review(self, review: ReviewPayload) -> tuple[GerritTarget, str]:
        target = self._target
        meta = review.get("review")
        if target is None and isinstance(meta, dict):
            raw = meta.get("diff_path")
            if raw:
                target = str(raw)
        if target is None:
            raise ReviewPublisherError("Gerrit target is required")
        try:
            return parse_gerrit_identifier(target), target
        except DiffSourceError as exc:
            raise ReviewPublisherError(str(exc)) from exc

    async def publish(
        self,
        review: ReviewPayload,
        *,
        mode: PublishMode = "dry_run",
    ) -> PublishResult:
        target, raw_target = self._target_from_review(review)
        fingerprint = review_fingerprint(review)
        payload = build_gerrit_review_payload(review, fingerprint)
        change_id = gerrit_rest_id(target.change)
        revision_id = gerrit_rest_id(target.revision)
        endpoint = (
            f"{target.base_url}/changes/{change_id}/revisions/"
            f"{revision_id}/review"
        )
        http_payload = {"method": "POST", "url": endpoint, "json": payload}

        if mode in {"dry_run", "draft"}:
            action = "dry_run" if mode == "dry_run" else "draft_payload"
            return PublishResult(
                platform="gerrit",
                mode=mode,
                fingerprint=fingerprint,
                target=raw_target,
                action=action,
                submitted=False,
                payloads=(http_payload,),
            )

        async with self._session_factory() as session:
            async with session.post(
                endpoint,
                headers=self._headers(),
                json=payload,
            ) as resp:
                if resp.status not in {200, 201, 204}:
                    raise ReviewPublisherError(
                        f"failed to publish Gerrit review (HTTP {resp.status})"
                    )

        return PublishResult(
            platform="gerrit",
            mode=mode,
            fingerprint=fingerprint,
            target=raw_target,
            action="submitted",
            submitted=True,
            payloads=(http_payload,),
        )
